In [2]:
import pandas as pd
from joblib import load
import numpy as np

from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, matthews_corrcoef, confusion_matrix

In [3]:
scaler_instance = load("../../results/rmssd/scaler.joblib")
knn_model = load("../../results/rmssd/knn_model.joblib")
rf_model = load("../../results/rmssd/rf_model.joblib")
svm_model = load("../../results/rmssd/svm_model.joblib")
dt_model = load("../../results/rmssd/dt_model.joblib")

In [4]:
val_data = pd.read_csv("../../process_dataset/rmssd/val_data.csv")
test_data = pd.read_csv("../../process_dataset/rmssd/test_data.csv")

y_val = np.load("../../process_dataset/rmssd/y_val.npy")
y_test = np.load("../../process_dataset/rmssd/y_test.npy")

In [5]:
val_data_scaler = scaler_instance.transform(val_data.values)
test_data_scaler = scaler_instance.transform(test_data.values)

In [6]:
predict_val = knn_model.predict(X=val_data_scaler)
predict_test = knn_model.predict(X=test_data_scaler)

/home/dmedina/miniconda3/envs/data_driven_library/lib/python3.9/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
/home/dmedina/miniconda3/envs/data_driven_library/lib/python3.9/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [7]:
predict_val_rf = rf_model.predict(X=val_data_scaler)

/home/dmedina/miniconda3/envs/data_driven_library/lib/python3.9/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [8]:
predict_test_rf = rf_model.predict(X=test_data_scaler)
predict_test_knn = knn_model.predict(X=test_data_scaler)

/home/dmedina/miniconda3/envs/data_driven_library/lib/python3.9/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/dmedina/miniconda3/envs/data_driven_library/lib/python3.9/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [9]:
acc_value = accuracy_score(y_pred=predict_val, y_true=y_val) 
recall_value = recall_score(y_pred=predict_val, y_true=y_val)
precision_value = precision_score(y_pred=predict_val, y_true=y_val) 
f1_value = f1_score(y_pred=predict_val, y_true=y_val)
mcc_value = matthews_corrcoef(y_pred=predict_val, y_true=y_val)
cm = confusion_matrix(y_pred=predict_val, y_true=y_val)

[acc_value, recall_value, precision_value, f1_value, mcc_value, cm]

[0.4895833333333333,
 0.2558139534883721,
 0.39285714285714285,
 0.3098591549295775,
 -0.07104869098008382,
 array([[36, 17],
        [32, 11]])]

In [10]:
acc_value = accuracy_score(y_pred=predict_val_rf, y_true=y_val) 
recall_value = recall_score(y_pred=predict_val_rf, y_true=y_val)
precision_value = precision_score(y_pred=predict_val_rf, y_true=y_val) 
f1_value = f1_score(y_pred=predict_val_rf, y_true=y_val)
mcc_value = matthews_corrcoef(y_pred=predict_val_rf, y_true=y_val)
cm = confusion_matrix(y_pred=predict_val_rf, y_true=y_val)

[acc_value, recall_value, precision_value, f1_value, mcc_value, cm]

[0.5416666666666666,
 0.27906976744186046,
 0.48,
 0.35294117647058815,
 0.03828418303335342,
 array([[40, 13],
        [31, 12]])]

In [11]:
acc_value = accuracy_score(y_pred=predict_test_rf, y_true=y_test) 
recall_value = recall_score(y_pred=predict_test_rf, y_true=y_test)
precision_value = precision_score(y_pred=predict_test_rf, y_true=y_test) 
f1_value = f1_score(y_pred=predict_test_rf, y_true=y_test)
mcc_value = matthews_corrcoef(y_pred=predict_test_rf, y_true=y_test)
cm = confusion_matrix(y_pred=predict_test_rf, y_true=y_test)

[acc_value, recall_value, precision_value, f1_value, mcc_value, cm]

[0.660377358490566,
 0.3125,
 0.4166666666666667,
 0.35714285714285715,
 0.1352631370262771,
 array([[30,  7],
        [11,  5]])]

In [12]:
acc_value = accuracy_score(y_pred=predict_test_knn, y_true=y_test) 
recall_value = recall_score(y_pred=predict_test_knn, y_true=y_test)
precision_value = precision_score(y_pred=predict_test_knn, y_true=y_test) 
f1_value = f1_score(y_pred=predict_test_knn, y_true=y_test)
mcc_value = matthews_corrcoef(y_pred=predict_test_knn, y_true=y_test)
cm = confusion_matrix(y_pred=predict_test_knn, y_true=y_test)

[acc_value, recall_value, precision_value, f1_value, mcc_value, cm]

[0.5660377358490566,
 0.25,
 0.26666666666666666,
 0.2580645161290323,
 -0.04820141084643202,
 array([[26, 11],
        [12,  4]])]

In [13]:
rf_model.predict_proba(X=test_data_scaler)

/home/dmedina/miniconda3/envs/data_driven_library/lib/python3.9/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([[0.57, 0.43],
       [0.58, 0.42],
       [0.78, 0.22],
       [0.64, 0.36],
       [0.55, 0.45],
       [0.71, 0.29],
       [0.71, 0.29],
       [0.84, 0.16],
       [0.57, 0.43],
       [0.71, 0.29],
       [0.61, 0.39],
       [0.75, 0.25],
       [0.57, 0.43],
       [0.56, 0.44],
       [0.76, 0.24],
       [0.89, 0.11],
       [0.55, 0.45],
       [0.84, 0.16],
       [0.33, 0.67],
       [0.85, 0.15],
       [0.64, 0.36],
       [0.64, 0.36],
       [0.23, 0.77],
       [0.52, 0.48],
       [0.54, 0.46],
       [0.64, 0.36],
       [0.22, 0.78],
       [0.89, 0.11],
       [0.38, 0.62],
       [0.83, 0.17],
       [0.47, 0.53],
       [0.54, 0.46],
       [0.54, 0.46],
       [0.67, 0.33],
       [0.4 , 0.6 ],
       [0.3 , 0.7 ],
       [0.5 , 0.5 ],
       [0.67, 0.33],
       [0.59, 0.41],
       [0.73, 0.27],
       [0.42, 0.58],
       [0.34, 0.66],
       [0.59, 0.41],
       [0.61, 0.39],
       [0.56, 0.44],
       [0.7 , 0.3 ],
       [0.43, 0.57],
       [0.25,