In [8]:
import pandas as pd
from joblib import load
import numpy as np

from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, matthews_corrcoef, confusion_matrix

In [15]:
scaler_instance = load("../results/scaler.joblib")
knn_model = load("../results/knn_model.joblib")
rf_model = load("../results/rf_model.joblib")
svm_model = load("../results/svm_model.joblib")
dt_model = load("../results/dt_model.joblib")

In [10]:
val_data = pd.read_csv("../process_dataset/val_data.csv")
test_data = pd.read_csv("../process_dataset/test_data.csv")

y_val = np.load("../process_dataset/y_val.npy")
y_test = np.load("../process_dataset/y_test.npy")

In [6]:
val_data_scaler = scaler_instance.transform(val_data.values)
test_data_scaler = scaler_instance.transform(test_data.values)

In [12]:
predict_val = knn_model.predict(X=val_data_scaler)
predict_test = knn_model.predict(X=test_data_scaler)

/home/dmedina/miniconda3/envs/data_driven_library/lib/python3.9/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
/home/dmedina/miniconda3/envs/data_driven_library/lib/python3.9/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [16]:
predict_val_rf = rf_model.predict(X=val_data_scaler)

/home/dmedina/miniconda3/envs/data_driven_library/lib/python3.9/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [18]:
predict_test_rf = rf_model.predict(X=test_data_scaler)
predict_test_knn = knn_model.predict(X=test_data_scaler)

/home/dmedina/miniconda3/envs/data_driven_library/lib/python3.9/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/dmedina/miniconda3/envs/data_driven_library/lib/python3.9/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [14]:
acc_value = accuracy_score(y_pred=predict_val, y_true=y_val) 
recall_value = recall_score(y_pred=predict_val, y_true=y_val)
precision_value = precision_score(y_pred=predict_val, y_true=y_val) 
f1_value = f1_score(y_pred=predict_val, y_true=y_val)
mcc_value = matthews_corrcoef(y_pred=predict_val, y_true=y_val)
cm = confusion_matrix(y_pred=predict_val, y_true=y_val)

[acc_value, recall_value, precision_value, f1_value, mcc_value, cm]

[0.4895833333333333,
 0.2558139534883721,
 0.39285714285714285,
 0.3098591549295775,
 -0.07104869098008382,
 array([[36, 17],
        [32, 11]])]

In [17]:
acc_value = accuracy_score(y_pred=predict_val_rf, y_true=y_val) 
recall_value = recall_score(y_pred=predict_val_rf, y_true=y_val)
precision_value = precision_score(y_pred=predict_val_rf, y_true=y_val) 
f1_value = f1_score(y_pred=predict_val_rf, y_true=y_val)
mcc_value = matthews_corrcoef(y_pred=predict_val_rf, y_true=y_val)
cm = confusion_matrix(y_pred=predict_val_rf, y_true=y_val)

[acc_value, recall_value, precision_value, f1_value, mcc_value, cm]

[0.5104166666666666,
 0.2558139534883721,
 0.4230769230769231,
 0.3188405797101449,
 -0.03044274661477632,
 array([[38, 15],
        [32, 11]])]

In [19]:
acc_value = accuracy_score(y_pred=predict_test_rf, y_true=y_test) 
recall_value = recall_score(y_pred=predict_test_rf, y_true=y_test)
precision_value = precision_score(y_pred=predict_test_rf, y_true=y_test) 
f1_value = f1_score(y_pred=predict_test_rf, y_true=y_test)
mcc_value = matthews_corrcoef(y_pred=predict_test_rf, y_true=y_test)
cm = confusion_matrix(y_pred=predict_test_rf, y_true=y_test)

[acc_value, recall_value, precision_value, f1_value, mcc_value, cm]

[0.6415094339622641,
 0.3125,
 0.38461538461538464,
 0.3448275862068966,
 0.10273355825475915,
 array([[29,  8],
        [11,  5]])]

In [20]:
acc_value = accuracy_score(y_pred=predict_test_knn, y_true=y_test) 
recall_value = recall_score(y_pred=predict_test_knn, y_true=y_test)
precision_value = precision_score(y_pred=predict_test_knn, y_true=y_test) 
f1_value = f1_score(y_pred=predict_test_knn, y_true=y_test)
mcc_value = matthews_corrcoef(y_pred=predict_test_knn, y_true=y_test)
cm = confusion_matrix(y_pred=predict_test_knn, y_true=y_test)

[acc_value, recall_value, precision_value, f1_value, mcc_value, cm]

[0.5660377358490566,
 0.25,
 0.26666666666666666,
 0.2580645161290323,
 -0.04820141084643202,
 array([[26, 11],
        [12,  4]])]

In [21]:
rf_model.predict_proba(X=test_data_scaler)

/home/dmedina/miniconda3/envs/data_driven_library/lib/python3.9/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([[0.54, 0.46],
       [0.55, 0.45],
       [0.81, 0.19],
       [0.65, 0.35],
       [0.5 , 0.5 ],
       [0.66, 0.34],
       [0.71, 0.29],
       [0.84, 0.16],
       [0.61, 0.39],
       [0.78, 0.22],
       [0.66, 0.34],
       [0.78, 0.22],
       [0.57, 0.43],
       [0.54, 0.46],
       [0.75, 0.25],
       [0.87, 0.13],
       [0.66, 0.34],
       [0.85, 0.15],
       [0.24, 0.76],
       [0.86, 0.14],
       [0.66, 0.34],
       [0.69, 0.31],
       [0.17, 0.83],
       [0.51, 0.49],
       [0.54, 0.46],
       [0.6 , 0.4 ],
       [0.29, 0.71],
       [0.87, 0.13],
       [0.41, 0.59],
       [0.74, 0.26],
       [0.64, 0.36],
       [0.54, 0.46],
       [0.42, 0.58],
       [0.76, 0.24],
       [0.48, 0.52],
       [0.35, 0.65],
       [0.59, 0.41],
       [0.72, 0.28],
       [0.63, 0.37],
       [0.64, 0.36],
       [0.31, 0.69],
       [0.31, 0.69],
       [0.54, 0.46],
       [0.64, 0.36],
       [0.49, 0.51],
       [0.59, 0.41],
       [0.44, 0.56],
       [0.26,